# Permalinks
permalink:           pretty

# Setup
title:               星星
tagline:             星星的自言自语
url:                 http://127.0.0.1:55555/
baseurl:             ""
paginate: 5  
paginate_path: "page:num"

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
